CREATE TABLE IF NOT EXISTS article (
    id CHAR(26) PRIMARY KEY,
    title VARCHAR(120),
    content MEDIUMTEXT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

